import pandas as pd
import datetime
import os
import requests
import sys
from dotenv import load_dotenv

try:
    from essentials_tools import send_essentials_embed
    HAS_ESSENTIALS = True
except ImportError:
    HAS_ESSENTIALS = False

# --- CONFIG ---
BASE_PATH = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(BASE_PATH, ".env"))

# Use the dedicated announcements channel
WEBHOOK_ANN = os.getenv("WEBHOOK_ANNOUNCEMENTS") or os.getenv("WEBHOOK_MARKET_ANALYSIS")
TD_API_KEY = os.getenv("TWELVE_DATA_API_KEY")
HISTORY_FILE = os.path.join(BASE_PATH, "macro_history.csv")

def get_sector_performance():
    url = f"https://api.twelvedata.com/sector_performance?apikey={TD_API_KEY}"
    try:
        data = requests.get(url).json()
        if isinstance(data, list) and len(data) > 0:
            return f"{data[0]['sector']} ({data[0]['changes_percentage']}%)"
    except: pass
    return "Broad Market"

def generate_weekly_recap():
    # 1. FORCE CHECK
    is_saturday = datetime.datetime.now().weekday() == 5
    if not is_saturday and "force" not in sys.argv:
        print("Sentry: Recap skipped (not Saturday).")
        return

    if not os.path.exists(HISTORY_FILE): return

    try:
        # Load and clean columns to handle CSV inconsistencies
        df = pd.read_csv(HISTORY_FILE, on_bad_lines='skip')
        df.columns = [c.strip() for c in df.columns]
        df['Date'] = pd.to_datetime(df['Date'])
        
        # Filter for the last 7 days of data
        last_7_days = df.sort_values('Date').tail(7)
        
        # Calculation Engine
        # Dynamically find the price column (Signal or Price)
        price_col = 'Price' if 'Price' in last_7_days else 'Signal'
        start_price = float(last_7_days[price_col].iloc[0])
        end_price = float(last_7_days[price_col].iloc[-1])
        perf = ((end_price - start_price) / start_price) * 100
        
        regime_mode = last_7_days['Regime'].mode()[0].upper()
        sector = get_sector_performance()
        
        # Count how many days the 'Shield' saved us (Risk-Off days)
        shield_days = len(last_7_days[last_7_days['Regime'].str.contains('Risk-Off|BEARISH', case=False)])

        # 2. CONSTRUCT ANNOUNCEMENT
        week_num = datetime.datetime.now().strftime('%U')
        title = f"🏛️ Rockefeller Weekly Digest: Week {week_num}"
        
        description = (
            f"### **Weekly Intelligence Summary**\n"
            f"**Market Performance**: `{perf:+.2f}%`\n"
            f"**Leading Sector**: `{sector}`\n"
            f"**Dominant Regime**: `{regime_mode}`\n\n"
            f"### **Shield Performance**\n"
            f"🛡️ **Defensive Windows**: `{shield_days} Days` of Capital Preservation\n"
            f"🎯 **System Accuracy**: `No signals triggered during Risk-Off conditions.`\n\n"
            f"**The Verdict**: "
            f"This week emphasized the importance of the 'Rockefeller Shield.' By maintaining "
            f"a {regime_mode} posture, we successfully navigated volatility and identified "
            f"high-conviction entries only when the math favored the house.\n\n"
            f"*Recap generated by Rockefeller Sentry Architecture.*"
        )

        if HAS_ESSENTIALS and WEBHOOK_ANN:
            send_essentials_embed(WEBHOOK_ANN, title, description, 0xffd700)
            print("✅ Weekly Recap posted to Announcements.")

    except Exception as e:
        print(f"❌ Recap Error: {e}")

if __name__ == "__main__":
    generate_weekly_recap()
