import os
import sys
import pytz
import logging
import datetime
import requests
from dotenv import load_dotenv
from database import EcosystemDatabase

# 1. Initialize Logger & Database
logger = logging.getLogger("Morning_Brief")
if not logger.handlers:
    ch = logging.StreamHandler(sys.stdout)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
logger.setLevel(logging.INFO)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(BASE_DIR, ".env"))
db = EcosystemDatabase()

WEBHOOK_MARKET = os.getenv("WEBHOOK_MARKET_ANALYSIS")

try:
    from essentials_tools import send_essentials_embed
    HAS_ESSENTIALS = True
except ImportError:
    HAS_ESSENTIALS = False

def check_market_status(td_key):
    """Validates if the NYSE is open today."""
    try:
        res = requests.get(f"https://api.twelvedata.com/market_state?apikey={td_key}", timeout=5).json()
        for market in res:
            if market.get("country") == "United States" and market.get("code") == "NYSE":
                return market.get("is_market_open", True)
    except Exception as e:
        logger.error(f"Market state fetch failed: {e}")
    return True

def get_fear_and_greed():
    """Fetches real-time market Fear & Greed context."""
    try:
        url = "https://api.alternative.me/fng/?limit=1"
        response = requests.get(url, timeout=5).json()
        data = response['data'][0]
        # Returns format like: "72 (Greed)"
        return f"{data['value']} ({data['value_classification']})"
    except Exception as e:
        logger.error(f"Failed to fetch Fear & Greed: {e}")
        return "N/A"

def load_crypto_state_context():
    """Pulls live crypto data from the database."""
    context = {"btc_price": "N/A", "eth_price": "N/A", "has_crypto": False}
    # Future integration: Pull actual crypto state from db once volatility_sentry writes it
    return context

def generate_morning_brief(is_test=False):
    td_key = os.getenv("TWELVE_DATA_API_KEY")
    
    # 1. Market Open Gatekeeper
    if not is_test:
        is_open = check_market_status(td_key)
        if not is_open:
            logger.info("Market Holiday Detected. Issuing standby notice.")
            title = "🌅 Rockefeller Morning Intelligence Briefing [MARKET CLOSED]"
            description = f"### **System Standby: Market Holiday**\nCurrently, markets are closed. Normal operations will resume at the next active trading bell."
            if HAS_ESSENTIALS and WEBHOOK_MARKET:
                send_essentials_embed(WEBHOOK_MARKET, title, description, 0x95a5a6)
            return

    # 2. State Extraction
    tz_h = pytz.timezone('US/Hawaii')
    now = datetime.datetime.now(tz_h)
    
    regime_data = db.get_state("market_regime", {"regime": "NEUTRAL", "vix_status": "STABLE", "rsi_shield_limit": 66})
    regime = regime_data.get("regime", "NEUTRAL")
    vix_status = regime_data.get("vix_status", "STABLE")
    rsi_limit = regime_data.get("rsi_shield_limit", 66)
    
    crypto_ctx = load_crypto_state_context()

    # 3. Tactical Posture Logic
    if vix_status == "STORM":
        color = 0xe74c3c 
        posture = "🛡️ DEFENSIVE: Shield is ACTIVE. Capital preservation priority."
        objectives = ["1. NO NEW ENTRIES: Volatility exceeds safety thresholds.", "2. CASH IS A POSITION: Wait for VIX to mean-revert."]
    elif vix_status == "ELEVATED":
        color = 0xf1c40f 
        posture = "⚖️ MEASURED: Volatility is rising. Size positions at 50%."
        objectives = ["1. TIGHT SHIELD: Only entries with RSI < 55.", "2. MONITOR VIX: Any spike above 22 triggers lockdown."]
    else:
        color = 0x2ecc71 
        posture = "🚀 OFFENSIVE: Conditions are STABLE. Execute at full size."
        objectives = ["1. ALPHA HUNT: Follow signals for high-conviction entries.", "2. RSI LIMIT: Standard < 66 threshold applies."]

    title = "🌅 Rockefeller Morning Intelligence Briefing" + (" [TEST]" if is_test else "")
    objective_text = "\n".join(objectives)
    
    fg_status = get_fear_and_greed()

    desc_lines = [
        f"### **Daily Battle Plan: {now.strftime('%b %d, %Y')}**",
        f"**Tactical Posture**: {posture}\n",
        f"📊 **Core Equity Index Metrics**:",
        f"┣ **Market Regime**: `{regime}`",
        f"┣ **Volatility Sentry**: `{vix_status}`",
        f"┣ **Fear & Greed**: `{fg_status}`",  # <-- INJECTED HERE
        f"┗ **RSI Shield**: `Active < {rsi_limit}`\n"
    ]

    desc_lines.extend([f"🛡️ **Tactical Objectives**:", f"{objective_text}\n", f"*Generated by Rockefeller Cross-Asset Architecture.*"])
    description = "\n".join(desc_lines)

    # 4. Dispatch
    if HAS_ESSENTIALS and WEBHOOK_MARKET:
        if send_essentials_embed(WEBHOOK_MARKET, title, description, color):
            logger.info(f"Cross-Asset Morning Intelligence brief dispatched for {vix_status} regime.")
        else:
            logger.error("Failed to dispatch intelligence brief to Discord.")

if __name__ == "__main__":
    is_test_mode = len(sys.argv) > 1 and sys.argv[1].lower() in ["test", "force"]
    generate_morning_brief(is_test=is_test_mode)

    # Ensure get_fear_and_greed() returns a value
    try:
        fg_status = get_fear_and_greed()
    except Exception:
        fg_status = "Data Unavailable"

    desc_lines = [
        f"### **Daily Battle Plan: {now.strftime('%b %d, %Y')}**",
        f"**Tactical Posture**: {posture}\n",
        f"📊 **Core Equity Index Metrics**:",
        f"┣ **Market Regime**: `{regime}`",
        f"┣ **Volatility Sentry**: `{vix_status}`",
        f"┣ **Fear & Greed**: `{fg_status}`",
        f"┗ **RSI Shield**: `Active < {rsi_limit}`\n"
