import os
import json
import pytz
import datetime
from dotenv import load_dotenv

try:
    from essentials_tools import send_essentials_embed
    HAS_ESSENTIALS = True
except ImportError:
    HAS_ESSENTIALS = False

# --- 1. CONFIGURATION ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(BASE_DIR, ".env"))

WEBHOOK_MARKET = os.getenv("WEBHOOK_MARKET_ANALYSIS")
REGIME_LEDGER = os.path.join(BASE_DIR, "market_regime.json")

def generate_morning_brief():
    """Consumes Ecosystem Ledger to produce a high-conviction daily battle plan."""
    tz_h = pytz.timezone('Pacific/Honolulu')
    now = datetime.datetime.now(tz_h)
    
    # 1. Load Data from Ecosystem Ledger
    try:
        with open(REGIME_LEDGER, "r") as f:
            data = json.load(f)
            regime = data.get("regime", "NEUTRAL")
            vix_status = data.get("vix_status", "STABLE")
            rsi_limit = data.get("rsi_shield_limit", 66)
            futures_pulse = data.get("futures_pulse", "🟡 NEUTRAL")
            
            # Check for active threats or overrides
            system_override = data.get("system_override", False)
            active_threats = data.get("active_threats", [])
    except Exception as e:
        print(f"⚠️ Ledger Load Failed: {e}")
        regime, vix_status, rsi_limit, system_override = "NEUTRAL", "UNKNOWN", 66, False
        futures_pulse = "⚪ UNKNOWN"
        active_threats = []

    # 2. Determine Rockefeller Tone & Tactical Posture
    if system_override or vix_status == "STORM":
        color = 0xe74c3c  # Red (Defensive)
        posture = "🛡️ DEFENSIVE: Shield is ACTIVE. Capital preservation priority."
        objectives = [
            "1. NO NEW ENTRIES: Market volatility exceeds safety thresholds.",
            "2. EXIT TRAILING: Tighten stops on all open positions.",
            "3. CASH IS A POSITION: Wait for VIX to mean-revert below 20."
        ]
    elif vix_status == "ELEVATED":
        color = 0xf1c40f  # Yellow (Cautious)
        posture = "⚖️ MEASURED: Volatility is rising. Size positions at 50%."
        objectives = [
            "1. TIGHT SHIELD: Only entries with RSI < 55 are valid.",
            "2. SCALP FOCUS: Target 4-8 tick moves only.",
            "3. MONITOR VIX: Any spike above 22 triggers immediate lockdown."
        ]
    else:
        color = 0x2ecc71  # Green (Offensive)
        posture = "🚀 OFFENSIVE: Conditions are STABLE. Execute at full size."
        objectives = [
            "1. ALPHA HUNT: Follow #trade-signals for high-conviction entries.",
            "2. TREND ALIGNMENT: Prioritize symbols showing Whale Accumulation.",
            "3. RSI LIMIT: Standard < 66 threshold applies."
        ]

    # 3. Build Intelligence Embed
    title = "🌅 Rockefeller Morning Intelligence"
    
    # Combine Objectives into a string
    objective_text = "\n".join(objectives)
    
    description = (
        f"### **Daily Battle Plan: {now.strftime('%b %d, %Y')}**\n"
        f"**Tactical Posture**: {posture}\n\n"
        f"**Ecosystem Metrics**:\n"
        f"┣ **Market Regime**: `{regime}`\n"
        f"┣ **Volatility Sentry**: `{vix_status}`\n"
        f"┣ **Futures Pulse**: `{futures_pulse}`\n"
        f"┗ **RSI Shield**: `Active < {rsi_limit}`\n\n"
        f"**Tactical Objectives**:\n"
        f"{objective_text}\n\n"
        f"*Recap generated by Rockefeller Sentry Architecture. Dispatched at {now.strftime('%H:%M HST')}.*"
    )

    if HAS_ESSENTIALS and WEBHOOK_MARKET:
        send_essentials_embed(WEBHOOK_MARKET, title, description, color)
        print(f"✅ Morning Intelligence dispatched for {vix_status} regime.")
    else:
        print("❌ Dispatch failed: Check Webhook/Essentials tools.")

if __name__ == "__main__":
    generate_morning_brief()
